apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAg2ZUiru/Gi8d9VsRjT/M3z2nmCAdVlKfEu2j1aadJTgTAibFOrpLl54R+IxKQrjKVNA0KMA5Mz8F0Nkg+HHyqNDefsRoz2Rd3nYAFZGR8/gr0tbIVMBkb1kr4hueRCa+tNIbbBKWaiAtwgUFJzbSMf3TDHMF0B8eudmiSYjP92BNUYpU/KkW9z+w/hnsvqNi/EaDHzoDZs2KNgI9l/1TV+1VvE9xyqYAZU7JDgjLD8OwLNUJWpT4mTaTy5i9eFxVBPOz52XfP8086IL9qaHLnUM1T8V326RfHHdxF68UpOTUlm7swiNIIzjV+B4euNRazOfvanjirMAANNW+dlv8vEScRzeZwzsXHjSN71shYcE9/uLmbo28qR+aWqLL3X/c4a25LNdErGIcEP/EKB+kApzpDUKBvWEYol+EXQa340IxRu5xVuqsktHNG16Cky0xFEWhkiGDoZfc0bCdSVI27T7/NQctB6iTPVQIj/HLNTrLJU8UEzh4sfjuEZi20D2m26nCjjDuDYhynzqjasJksRAqBRzZjiz9MSbnlbjtH0KJjFVXalrGSIQ9vYZK2nd4M2l/WU+UI057gi10O9AQqdZBSvO9xhsDU9/o40P2NxlUeRsQB1PRL7B79CDjfTRLThUoB/4SfUTcw6a4WODPHL9mYVlpcDWUNHpnPNAqcLHcei8p3JT9YHUEuSnZ2ASHvlszE2XWhQQ==
    DB_USER: AgBpOZpt+cJDpCpUpJmvEzhZMbYWGbTmOXITjGX8aJmdsExIivQXTzwHIHvZ81hAt3clALrNllv+zIoScvgHB+UkZ0DVuzo52pbvDc2QxvGduu2BMAKlaeJJ0RrIBhY8B7E/xXWD0N76Ck9NfqGshu3KMiVaARlw929qMGhHUmJU/QqWc8Rqf1THB4vvkFNq24RW7ouVK/KTfKxy6QFlfePIrcRnlNHkQyvTvkBHRtgOojnWnY1v6qaDifFAdl26H5FEslTO88AKMN7p2UksNypPOJXxJTQHIjLNEyfw6r2WLCKWBEagX98lhR6RKaR6zwM+C3OufQAT7p9B0y0Ysl4BILnv5/6ztdIHqTP4/OW11dD1RhUNO9PBW88gfZn7WT/DjYDTMxJy/ZI1/qs6ifarUsmuzxUvnO0ynpl+lQ/oZtrbJrbpMz1CPzhHiFMT5CW6F9Yjvwi8b8xIUblu2+KpRRyGRYYlHCty5g0pVggdjechjmGvftcHrgU5eTG5Wj6VjVIIpy0gZOZJeeMaWzOhb61qyyhOuAdpC5t/PZU1eyMbuL8ldO0UI5W1aI/vrzJ6uTD1wpo2kK91J/E0LaaXI7iVo0bv+iWUgPcFZgLV5K71FLPAuAu9dcVlwampxVtXtrikETX6jFv/ucaUIpp4Q5NALXOUBlBPHh9jxYi7M/JoS3xVhVXvvLTyHc9XZJeQzZi63rIkkw==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

