apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgCaAxGhzAad0ECqGgQtoBEvBg4Z80r5OqULm3MII6Qg2lTjUf90QD060QwEVn4URa4ypLYr0ZfGc/Hq+fdkGERf/5+4//gM6Pnc9lWvU5BW5hIQBYh9BTBbriFVcfHuKIn8ux+ZePzLzq1Frlsqr0+gLqkfIklrcHmxGYwxERWUCAZIMW6OnYDVQk9Wu22Wa0JLkOH3AkXDjZ1Xecz2tNZ0erm32igDiXhZmlTJcCAg6TVWBD2wGosnHgv4Q1+b/km9hDcfZHbFUx1KMiSKG90STil6YLuk/aUcHqSDISU6ADYxttITrApfjdGk63rruGnBpnrmb1Vy5zjkBPabVxoJBAj6ac2ugSM+RRJzy1zS3ivN97nhpc00OCQhnOAI6SQzelH6BVqco6g2VLTeClWgPzzpkeIuD/tx5LNq/yLfRJZuLx96WJTUMWFn3up87aItMAsQScRLGWMURnzuVnciPcm21E8Yz7+4745h1Afe6TaF6tlvReTE++FYrZtXVfqlSbHFLDheQaQUFEyaarokgPLI8IMqDiERkhz8VeBVSl/Pynxk8C/ahqU69ypY/k9YVHACQfqxPHTeaSRvRkK7OwYcuUFgRrPZIBHK5Fj86r2E/Jbp9AXIEBt82vlH9GjWCX48uq385gVngadUY5VUkquPbeIZH09BY5ZL1+Hrs28A+8A471QUC6rAyj/Lmbd6lpByL/Fp3g==
    DB_USER: AgAVqJ7XYjGRrz5ESkGx9iDYA1MtMNiPa6zNND7AYAEycpjp3NZsV4KQ2Qu2McDk1qo9vSKf9wEnUb8nck63i/Jg8a8XtG53rBCBpRnk2uXCEFc9enDb47AuC8lShRRsB2WRfxlYWPV5zToJ9gSeiO68KCiUmLj6/ly9Q6ff1E/5Jxw0r6JG16FOIHUsn98SNmOf8oSbsrEMp8fIxX/grsJMdenKarFxU1I2T7Tfy6BcqwtgX3lRfnIZMELW/ctMoomd+XmEsUv8wTSNEfKi41cYcnYwFGUKeHCBfCXHb4w0Pnejs3GFSbXJhB8HUeXFFmaBVnRE2ylSqXmQgTWviuegBOhwRwN5fqZi4M+r1QYKuJfdQAqzbtXSAI3F41zrc1gQaZh0XIB5cgSirqnf2N7xEHM7MbQ+/Vn0pN/IXBOJ/Y0kGyv0kpuZQrwj3bTEe50iBevxVnlBzeEIP3jB0428LBDzqdvMmurywEckIZ8xjpacN9qRJjWJ82byUFpC3iutJ6okSLwMQZ+Ep1GnMuneqrDKL9plYunhISJet2jcbNEoduR9/EobzP9tl8P+IcSi2ww0H7nokkPzYjlBRq+ZKzfMmUhULcU5iUVJqT5b15AaaNiXEF2F+GFZICJsCVMYoeOEnFA6ikw3sk1004eoCzQjVKEpxQNdv6Z31ItaJ2jbTjfhH8tmJNCA3E9lU7VKN/bXVmYu2w==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

